// Decoding and the clip store (clip_store.h). Every file is generated by the test that decodes it:
// WAV in two sample formats, FLAC through a writer that stores samples verbatim, and a clip at
// 44.1 kHz that has to come out at the mix rate.
#include "audio_test_support.h"

#include <core/hash/hash.h>
#include <core/jobs/job_system.h>
#include <domain/audio/audio.h>

#include <doctest/doctest.h>

#include <cmath>

using namespace engine;
using namespace engine::audio;
using namespace engine::audio::test;

namespace {

std::span<const u8> bytes(const Vector<u8>& v) { return {v.data(), v.size()}; }

// Positive-going zero crossings per second of one channel: the frequency, to within a cycle.
f64 frequency(std::span<const f32> samples, u32 channels, u32 channel, u32 frames) {
  u32 crossings = 0;
  for (u32 i = 1; i < frames; ++i) {
    const f32 a = samples[(i - 1u) * channels + channel];
    const f32 b = samples[i * channels + channel];
    if (a < 0.0f && b >= 0.0f) ++crossings;
  }
  return static_cast<f64>(crossings) * static_cast<f64>(k_sample_rate) / static_cast<f64>(frames);
}

}  // namespace

TEST_CASE("a generated 16-bit stereo WAV decodes to exactly its samples") {
  const Vector<f32> left = reference_sine(4800, 440.0, 0.5);
  const Vector<f32> right = reference_sine(4800, 880.0, 0.25);
  Vector<f32> interleaved;
  for (u32 i = 0; i < 4800; ++i) {
    interleaved.push_back(left[i]);
    interleaved.push_back(right[i]);
  }
  const Vector<i16> pcm = to_s16(interleaved);
  const Vector<u8> file = wav_s16(pcm, 2, k_sample_rate);

  DecodedClip clip;
  REQUIRE(decode_clip(bytes(file), clip) == DecodeStatus::Ok);
  CHECK(clip.channels == 2u);
  CHECK(clip.source_channels == 2u);
  CHECK(clip.source_rate == k_sample_rate);
  REQUIRE(clip.frames == 4800u);
  REQUIRE(clip.samples.size() == 9600u);
  // 16-bit to float is a multiplication by 2^-15: exact, so the round trip is too.
  for (u32 i = 0; i < 9600; ++i)
    CHECK(clip.samples[i] == static_cast<f32>(pcm[i]) / 32768.0f);
}

TEST_CASE("a float WAV decodes bit for bit") {
  const Vector<f32> noise = lcg_noise(3000, 7, 0.9f);
  const Vector<u8> file = wav_f32(noise, 1, k_sample_rate);
  DecodedClip clip;
  REQUIRE(decode_clip(bytes(file), clip) == DecodeStatus::Ok);
  CHECK(clip.channels == 1u);
  REQUIRE(clip.frames == 3000u);
  for (u32 i = 0; i < 3000; ++i)
    CHECK(clip.samples[i] == noise[i]);
}

TEST_CASE("a generated FLAC decodes to exactly its samples") {
  // 10000 frames: two full 4096-sample blocks and a short last one.
  const Vector<f32> sine = reference_sine(10000, 1000.0, 0.7);
  Vector<f32> interleaved;
  for (u32 i = 0; i < 10000; ++i) {
    interleaved.push_back(sine[i]);
    interleaved.push_back(-sine[i]);
  }
  const Vector<i16> pcm = to_s16(interleaved);
  const Vector<u8> file = flac_s16(pcm, 2);
  DecodedClip clip;
  REQUIRE(decode_clip(bytes(file), clip) == DecodeStatus::Ok);
  CHECK(clip.channels == 2u);
  CHECK(clip.source_rate == k_sample_rate);
  REQUIRE(clip.frames == 10000u);
  for (u32 i = 0; i < 20000; ++i)
    CHECK(clip.samples[i] == static_cast<f32>(pcm[i]) / 32768.0f);
}

TEST_CASE("a 44.1 kHz clip is resampled to the mix rate at decode time") {
  // One second of a 918.75 Hz sine (a 48-sample period at 44.1 kHz), generated without libm so
  // that the file, and therefore the pinned hash below, is the same bytes on every toolchain.
  const Vector<f32> sine = exact_sine(44100, 48, 0.5f);
  const Vector<i16> pcm = to_s16(sine);
  const Vector<u8> file = wav_s16(pcm, 1, 44100);

  DecodedClip clip;
  REQUIRE(decode_clip(bytes(file), clip) == DecodeStatus::Ok);
  CHECK(clip.source_rate == 44100u);
  CHECK(clip.channels == 1u);
  // One second in is one second out, give or take the resampler's latency.
  CHECK(clip.frames >= 47990u);
  CHECK(clip.frames <= 48010u);
  // Still 918.75 Hz: the rate changed, the pitch did not.
  CHECK(frequency({clip.samples.data(), clip.samples.size()}, 1, 0, clip.frames) ==
        doctest::Approx(918.75).epsilon(0.002));
  // Still 0.5 in amplitude once the filter has settled.
  f32 peak = 0.0f;
  for (u32 i = 4800; i < clip.frames - 4800u; ++i)
    peak = std::fabs(clip.samples[i]) > peak ? std::fabs(clip.samples[i]) : peak;
  CHECK(static_cast<f64>(peak) == doctest::Approx(0.5).epsilon(0.02));
  // The decode is part of what a clip set is, so it is pinned like the mix: the filter's
  // coefficients come from libm's sin and cos in double and are rounded to f32, and the claim is
  // that the rounding absorbs any last-bit difference between C libraries
  // (docs/subsystems/audio.md, "Determinism"). Taken on MSVC; the Linux container build checks
  // GCC's and Clang's glibc.
  const u64 hash = hash_bytes(clip.samples.data(), clip.samples.size() * sizeof(f32));
  MESSAGE("44.1 kHz decode: " << clip.frames << " frames, hash " << hex64(hash));
  CHECK(hash == 0x4fd32be85084006dull);
}

TEST_CASE("more than two channels are folded to stereo") {
  Vector<f32> six;
  for (u32 i = 0; i < 2000; ++i)
    for (u32 c = 0; c < 6; ++c)
      six.push_back(c == 0 ? 0.25f : 0.0f);
  const Vector<u8> file = wav_f32(six, 6, k_sample_rate);
  DecodedClip clip;
  REQUIRE(decode_clip(bytes(file), clip) == DecodeStatus::Ok);
  CHECK(clip.source_channels == 6u);
  CHECK(clip.channels == 2u);
  CHECK(clip.frames == 2000u);
}

TEST_CASE("bytes that are not audio are refused, not guessed at") {
  DecodedClip clip;
  CHECK(decode_clip({}, clip) == DecodeStatus::UnknownFormat);
  Vector<u8> junk;
  for (u32 i = 0; i < 4096; ++i)
    junk.push_back(static_cast<u8>((i * 2654435761u) >> 24));
  CHECK(decode_clip(bytes(junk), clip) == DecodeStatus::UnknownFormat);
  CHECK(clip.frames == 0u);
  CHECK(clip.samples.empty());
}

TEST_CASE("the clip store decodes once per key and reports what it holds") {
  ClipStore store;
  const Vector<f32> sine = reference_sine(4800, 440.0, 0.5);
  const Vector<u8> file = wav_s16(to_s16(sine), 1, k_sample_rate);
  const Id128 key = clip_key(bytes(file));
  CHECK(key == clip_key(bytes(file)));

  const ClipHandle clip = store.load(key, bytes(file));
  REQUIRE(clip.is_valid());
  CHECK(store.state(clip) == ClipState::Ready);  // no job system: decoded inline
  CHECK(store.load(key, bytes(file)) == clip);
  CHECK(store.find(key) == clip);
  CHECK(store.count() == 1u);
  const ClipInfo info = store.info(clip);
  CHECK(info.frames == 4800u);
  CHECK(info.channels == 1u);
  CHECK(info.bytes == 4800u * sizeof(f32));
  CHECK(store.resident_bytes() == info.bytes);
  const ClipView view = store.view(clip);
  CHECK(view.samples != nullptr);
  CHECK(view.frames == 4800u);

  CHECK(store.state(ClipHandle{}) == ClipState::Invalid);
  CHECK(store.view(ClipHandle{}).samples == nullptr);
  CHECK_FALSE(store.find(Id128{1, 2}).is_valid());

  const Vector<u8> junk(64u, u8{0x55});
  const ClipHandle bad = store.load(Id128{3, 4}, bytes(junk));
  CHECK(store.state(bad) == ClipState::Failed);
  CHECK(store.view(bad).samples == nullptr);

  const Vector<f32> three(3, 0.0f);
  CHECK(store.state(store.add_pcm(Id128{5, 6}, three, 2)) == ClipState::Failed);  // 3 % 2 != 0
}

// Samples handed to the store are the only copy there is, so nothing evicts them: a clip past the
// budget with nothing evictable is refused (eviction_tests.cpp has the clips that can be evicted).
TEST_CASE("a clip past the budget is refused when nothing can be evicted for it") {
  ClipStoreConfig config;
  config.budget_bytes = 10000;
  ClipStore store(config);
  const Vector<f32> small(1000, 0.1f);  // 4000 bytes
  const Vector<f32> other(1000, 0.2f);
  const Vector<f32> more(1000, 0.3f);
  CHECK(store.state(store.add_pcm(Id128{0, 1}, small, 1)) == ClipState::Ready);
  CHECK(store.state(store.add_pcm(Id128{0, 2}, other, 1)) == ClipState::Ready);
  const ClipHandle third = store.add_pcm(Id128{0, 3}, more, 1);
  CHECK(store.state(third) == ClipState::OverBudget);
  CHECK(store.over_budget() == 1u);
  CHECK(store.resident_bytes() == 8000u);
  CHECK(store.state(store.find(Id128{0, 1})) == ClipState::Ready);
}

TEST_CASE("decodes run on the job system's efficiency pool and land ready") {
  jobs::JobSystemConfig jobs_config;
  jobs_config.performance_workers = 1;
  jobs_config.efficiency_workers = 2;
  jobs_config.pin_threads = false;
  jobs::JobSystem jobs(jobs_config);
  ClipStoreConfig config;
  config.jobs = &jobs;
  ClipStore store(config);

  Vector<Vector<u8>> files;
  for (u32 i = 0; i < 8; ++i) {
    const Vector<f32> sine = reference_sine(2400 + i * 100u, 200.0 + 50.0 * i, 0.5);
    files.push_back(wav_s16(to_s16(sine), 1 + (i % 2u), k_sample_rate));
  }
  const u64 executed_before = jobs.stats().jobs_executed;
  Vector<ClipHandle> handles;
  for (const Vector<u8>& file : files)
    handles.push_back(store.load(clip_key(bytes(file)), bytes(file)));
  store.wait();
  for (u32 i = 0; i < 8; ++i) {
    CHECK(store.state(handles[i]) == ClipState::Ready);
    const ClipInfo info = store.info(handles[i]);
    // Stereo files hold interleaved mono pairs here: frames are half the samples.
    CHECK(info.channels == 1u + (i % 2u));
    CHECK(info.frames == (2400u + i * 100u) / (1u + (i % 2u)));
  }
  CHECK(jobs.stats().jobs_executed >= executed_before + 8u);
}
