// The ECS backend (ADR-0028 seam 1). For every `@kind(component)` struct in a schema file it
// emits one call that registers the type with flecs under the schema's qualified name.
//
// **Why this is a header and not a source file.** The generated schema module sits in the core
// layer and must not link flecs; the registration must. Emitting a header solves both halves at
// once: it is compiled only where it is included, and ADR-0028 seam 5 already restricts who may
// include `<flecs.h>` to `domain/ecs`, `systems/`, `game/` and their tests and benches. So the
// file is always written — CMake needs a static output list, and a schema with no components
// still produces one — and is compiled only in a build that has the ECS capability, by a
// translation unit that was allowed to reach flecs anyway.
//
// **Why the body is one call per component and not a table of descriptors.** The mapping from a
// schema `Kind` to a flecs meta type is a judgement (which kinds map, what a Vec3 becomes, what
// happens to a `string`), and a judgement belongs in one reviewable place rather than in
// generated text. `engine::ecs::register_schema_component<T>()` holds it; this file only says
// which types to feed it.

#include "model.h"

#include <sstream>
#include <string>

namespace schemac {

std::string emit_ecs_header(const Model& model, const SchemaFile& file) {
  (void)model;
  std::ostringstream out;
  out << "// Generated by schemac from " << file.stem << ".schema. Do not edit; edit the schema.\n";
  out << "//\n";
  out << "// flecs registration for this schema's @kind(component) types (ADR-0028 seam 1).\n";
  out << "// Includes <flecs.h>, so only domain/ecs, systems/*, game/* and their tests and\n";
  out << "// benches may include it (ADR-0028 seam 5, tools/lint.ps1).\n";
  out << "#pragma once\n\n";
  out << "#include <domain/ecs/components.h>\n";
  out << "#include <schemas/" << file.stem << ".h>\n\n";

  const std::string ns = ns_to_cpp(file.ns);
  out << "namespace " << ns << " {\n\n";

  out << "// Registers every component " << file.stem << ".schema declares with `world`, under\n";
  out << "// its schema-qualified name, with member reflection for the fields that map onto\n";
  out << "// flecs meta and with the schema's @transient marking as the `ecs::Transient` tag.\n";
  out << "// Idempotent per world: a second call finds the components already there.\n";
  out << "inline void register_" << file.stem << "_components(::flecs::world& world) {\n";
  bool any = false;
  for (const StructDecl& s : file.structs) {
    if (!is_component(s)) continue;
    any = true;
    out << "  ::engine::ecs::register_schema_component<::" << ns << "::" << s.name << ">(world);\n";
  }
  if (!any) {
    out << "  // This schema declares no @kind(component) structs.\n";
    out << "  (void)world;\n";
  }
  out << "}\n\n";

  out << "}  // namespace " << ns << "\n";
  return out.str();
}

}  // namespace schemac
