#include "model.h"

#include <cstdlib>
#include <set>
#include <sstream>
#include <string>

namespace schemac {

namespace {

std::string kind_enum(const TypeExpr& t) {
  switch (t.kind) {
    case TypeExpr::Kind::Primitive: {
      if (t.name == "bool") return "Bool";
      if (t.name == "string") return "String";
      if (t.name == "bytes") return "Bytes";
      if (t.name == "id128") return "Id128";
      std::string k = t.name;
      k[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(k[0])));
      return k;  // u8 -> U8, f32 -> F32
    }
    case TypeExpr::Kind::Named: return t.resolved_is_enum ? "Enum" : "Struct";
    case TypeExpr::Kind::Optional: return "Optional";
    case TypeExpr::Kind::Array: return "Array";
    case TypeExpr::Kind::FixedArray: return "FixedArray";
    case TypeExpr::Kind::Map: return "Map";
  }
  return "Bool";
}

std::string kind_enum_for_primitive_name(const std::string& name) {
  TypeExpr t;
  t.kind = TypeExpr::Kind::Primitive;
  t.name = name;
  return kind_enum(t);
}

std::string info_symbol(const TypeExpr& t) {
  // a::b::schema_detail::Name_info
  const size_t sep = t.resolved_cpp.rfind("::");
  const std::string ns = sep == std::string::npos ? "" : t.resolved_cpp.substr(0, sep);
  const std::string name =
      sep == std::string::npos ? t.resolved_cpp : t.resolved_cpp.substr(sep + 2);
  return (ns.empty() ? "" : ns + "::") + "schema_detail::" + name + "_info";
}

// Emits a doc string as one or more `// ` comment lines at the given indent.
void emit_comment(std::ostringstream& out, const std::string& indent, const std::string& doc) {
  if (doc.empty()) return;
  size_t start = 0;
  while (start <= doc.size()) {
    const size_t nl = doc.find('\n', start);
    const std::string line =
        doc.substr(start, nl == std::string::npos ? std::string::npos : nl - start);
    out << indent << "// " << line << "\n";
    if (nl == std::string::npos) break;
    start = nl + 1;
  }
}

std::string default_initializer(const Field& f) {
  const TypeExpr& t = f.type;
  switch (f.default_kind) {
    case DefaultKind::None:
    case DefaultKind::Null:
    case DefaultKind::EmptyArray: return "{}";
    case DefaultKind::Bool: return f.default_text;
    case DefaultKind::Int:
      if (t.name == "f32") return f.default_text + ".0f";
      if (t.name == "f64") return f.default_text + ".0";
      if (t.name == "u64") return f.default_text + "ull";
      if (t.name == "i64") return f.default_text + "ll";
      return f.default_text;
    case DefaultKind::Float: return t.name == "f32" ? f.default_text + "f" : f.default_text;
    case DefaultKind::String: return "\"" + escape_cpp_string(f.default_text) + "\"";
    case DefaultKind::Ident: return t.resolved_cpp + "::" + f.default_text;
  }
  return "{}";
}

// Emits constexpr TypeRef constants for `t` and its element types; returns the outermost name.
std::string emit_type_ref(std::ostringstream& out, const TypeExpr& t, const std::string& prefix,
                          int& counter) {
  std::string element_ref, key_ref;
  if (t.element) element_ref = emit_type_ref(out, *t.element, prefix, counter);
  if (t.key) key_ref = emit_type_ref(out, *t.key, prefix, counter);
  const std::string name = prefix + "_r" + std::to_string(counter++);
  const std::string cpp = cpp_type(t);
  out << "constexpr engine::schema::TypeRef " << name << "{\n";
  out << "    .kind = engine::schema::Kind::" << kind_enum(t) << ",\n";
  out << "    .fixed_count = "
      << (t.kind == TypeExpr::Kind::FixedArray ? std::to_string(t.count) : "0") << ",\n";
  out << "    .size = sizeof(" << cpp << "),\n";
  out << "    .align = alignof(" << cpp << "),\n";
  out << "    .type = " << (t.kind == TypeExpr::Kind::Named ? "&" + info_symbol(t) : "nullptr")
      << ",\n";
  out << "    .element = " << (element_ref.empty() ? "nullptr" : "&" + element_ref) << ",\n";
  out << "    .key = " << (key_ref.empty() ? "nullptr" : "&" + key_ref) << ",\n";
  out << "    .optional_ops = "
      << (t.kind == TypeExpr::Kind::Optional ? "&engine::schema::OptionalOpsFor<" + cpp + ">::ops"
                                             : "nullptr")
      << ",\n";
  std::string array_ops = "nullptr";
  if (t.kind == TypeExpr::Kind::Array ||
      (t.kind == TypeExpr::Kind::Primitive && t.name == "bytes")) {
    array_ops = "&engine::schema::ArrayOpsFor<" + cpp + ">::ops";
  } else if (t.kind == TypeExpr::Kind::FixedArray) {
    array_ops = "&engine::schema::FixedArrayOpsFor<" + cpp + ">::ops";
  }
  out << "    .array_ops = " << array_ops << ",\n";
  out << "    .map_ops = "
      << (t.kind == TypeExpr::Kind::Map ? "&engine::schema::MapOpsFor<" + cpp + ">::ops"
                                        : "nullptr")
      << ",\n";
  out << "};\n";
  return name;
}

}  // namespace

std::string emit_cpp_header(const Model& model, const SchemaFile& file) {
  (void)model;
  std::ostringstream out;
  out << "// Generated by schemac from " << file.stem << ".schema. Do not edit; edit the schema.\n";
  out << "#pragma once\n\n";
  out << "#include <core/base/types.h>\n";
  out << "#include <core/containers/flat_map.h>\n";
  out << "#include <core/containers/vector.h>\n";
  out << "#include <core/ids/id128.h>\n";
  out << "#include <core/json/json_value.h>\n";
  out << "#include <core/math/math.h>\n";
  out << "#include <core/schema/type_info.h>\n\n";
  out << "#include <array>\n#include <optional>\n#include <string>\n";
  for (const std::string& imp : file.imports)
    out << "#include <schemas/" << imp << ".h>\n";
  out << "\n";

  const std::string ns = ns_to_cpp(file.ns);
  out << "namespace " << ns << " {\n\n";

  for (const EnumDecl& e : file.enums) {
    emit_comment(out, "", e.doc);
    out << "enum class " << e.name << " : engine::" << e.underlying << " {\n";
    for (const EnumValue& v : e.values) {
      emit_comment(out, "  ", v.doc);
      out << "  " << v.name << " = " << v.value << ",\n";
    }
    out << "};\n\n";
  }

  for (const StructDecl& s : file.structs) {
    emit_comment(out, "", s.doc);
    out << "struct " << s.name << " {\n";
    out << "  static constexpr engine::u16 k_schema_version = " << s.version << ";\n\n";
    for (const Field& f : s.fields) {
      emit_comment(out, "  ", f.doc);
      out << "  " << cpp_type(f.type) << " " << f.name;
      const std::string init = default_initializer(f);
      if (init == "{}") {
        out << "{};\n";
      } else {
        out << " = " << init << ";\n";
      }
    }
    out << "\n  bool operator==(const " << s.name << "&) const = default;\n";
    out << "};\n\n";
  }

  out << "namespace schema_detail {\n";
  for (const EnumDecl& e : file.enums)
    out << "extern const engine::schema::TypeInfo " << e.name << "_info;\n";
  for (const StructDecl& s : file.structs)
    out << "extern const engine::schema::TypeInfo " << s.name << "_info;\n";
  out << "}  // namespace schema_detail\n\n";
  out << "}  // namespace " << ns << "\n\n";

  out << "namespace engine::schema {\n";
  for (const EnumDecl& e : file.enums) {
    out << "template <>\ninline const TypeInfo& type_of<" << ns << "::" << e.name << ">() { return "
        << ns << "::schema_detail::" << e.name << "_info; }\n";
  }
  for (const StructDecl& s : file.structs) {
    out << "template <>\ninline const TypeInfo& type_of<" << ns << "::" << s.name << ">() { return "
        << ns << "::schema_detail::" << s.name << "_info; }\n";
  }
  out << "}  // namespace engine::schema\n";
  return out.str();
}

std::string emit_cpp_source(const Model& model, const SchemaFile& file) {
  (void)model;
  std::ostringstream out;
  out << "// Generated by schemac from " << file.stem << ".schema. Do not edit; edit the schema.\n";
  out << "#include <schemas/" << file.stem << ".h>\n\n";
  out << "#include <core/schema/ops.h>\n\n";
  out << "#include <cstddef>\n#include <span>\n\n";
  out << "#if defined(__clang__) || defined(__GNUC__)\n";
  out << "#pragma GCC diagnostic ignored \"-Winvalid-offsetof\"\n";
  out << "#endif\n\n";

  const std::string ns = ns_to_cpp(file.ns);
  out << "namespace " << ns << "::schema_detail {\n\n";
  out << "namespace {\n\n";

  for (const EnumDecl& e : file.enums) {
    out << "constexpr engine::schema::EnumValueInfo " << e.name << "_values[] = {\n";
    for (const EnumValue& v : e.values) {
      out << "    {\"" << v.name << "\", " << v.value << ", \"" << escape_cpp_string(v.doc)
          << "\"},\n";
    }
    out << "};\n\n";
  }

  for (const StructDecl& s : file.structs) {
    int counter = 0;
    std::vector<std::string> refs;
    for (const Field& f : s.fields)
      refs.push_back(emit_type_ref(out, f.type, s.name + "_" + f.name, counter));
    out << "\n";
    if (s.fields.empty()) {
      out << "constexpr std::span<const engine::schema::FieldInfo> " << s.name << "_fields{};\n\n";
    } else {
      out << "constexpr engine::schema::FieldInfo " << s.name << "_fields[] = {\n";
      for (size_t i = 0; i < s.fields.size(); ++i) {
        const Field& f = s.fields[i];
        std::string flags = "0";
        if (f.transient) flags += " | engine::schema::FieldFlag::transient";
        if (f.deprecated) flags += " | engine::schema::FieldFlag::deprecated";
        out << "    {\"" << f.name << "\", " << refs[i] << ", static_cast<engine::u32>(offsetof("
            << s.name << ", " << f.name << ")), " << f.since << ", static_cast<engine::u16>("
            << flags << "), \"" << escape_cpp_string(f.doc) << "\"},\n";
      }
      out << "};\n\n";
    }
  }
  out << "}  // namespace\n\n";

  for (const EnumDecl& e : file.enums) {
    out << "extern const engine::schema::TypeInfo " << e.name << "_info{\n";
    out << "    .qualified_name = \"" << file.ns << "." << e.name << "\",\n";
    out << "    .name = \"" << e.name << "\",\n";
    out << "    .ns = \"" << file.ns << "\",\n";
    out << "    .kind = engine::schema::Kind::Enum,\n";
    out << "    .size = sizeof(" << e.name << "),\n";
    out << "    .align = alignof(" << e.name << "),\n";
    out << "    .version = 1,\n";
    out << "    .tag = \"" << escape_cpp_string(e.tag) << "\",\n";
    out << "    .doc = \"" << escape_cpp_string(e.doc) << "\",\n";
    out << "    .fields = {},\n";
    out << "    .values = std::span<const engine::schema::EnumValueInfo>(" << e.name
        << "_values),\n";
    out << "    .enum_underlying = engine::schema::Kind::"
        << kind_enum_for_primitive_name(e.underlying) << ",\n";
    out << "    .ops = nullptr,\n";
    out << "};\n\n";
  }
  for (const StructDecl& s : file.structs) {
    out << "extern const engine::schema::TypeInfo " << s.name << "_info{\n";
    out << "    .qualified_name = \"" << file.ns << "." << s.name << "\",\n";
    out << "    .name = \"" << s.name << "\",\n";
    out << "    .ns = \"" << file.ns << "\",\n";
    out << "    .kind = engine::schema::Kind::Struct,\n";
    out << "    .size = sizeof(" << s.name << "),\n";
    out << "    .align = alignof(" << s.name << "),\n";
    out << "    .version = " << s.version << ",\n";
    out << "    .tag = \"" << escape_cpp_string(s.tag) << "\",\n";
    out << "    .doc = \"" << escape_cpp_string(s.doc) << "\",\n";
    if (s.fields.empty()) {
      out << "    .fields = " << s.name << "_fields,\n";
    } else {
      out << "    .fields = std::span<const engine::schema::FieldInfo>(" << s.name << "_fields),\n";
    }
    out << "    .values = {},\n";
    out << "    .enum_underlying = engine::schema::Kind::U32,\n";
    out << "    .ops = &engine::schema::StructOpsFor<" << s.name << ">::ops,\n";
    out << "};\n\n";
  }

  out << "namespace {\n";
  out << "const engine::schema::TypeInfo* const k_all_types[] = {\n";
  for (const EnumDecl& e : file.enums)
    out << "    &" << e.name << "_info,\n";
  for (const StructDecl& s : file.structs)
    out << "    &" << s.name << "_info,\n";
  out << "};\n";
  out << "const engine::schema::Registrar k_registrar(k_all_types, sizeof(k_all_types) / "
         "sizeof(k_all_types[0]));\n";
  out << "}  // namespace\n\n";
  out << "}  // namespace " << ns << "::schema_detail\n";
  return out.str();
}

}  // namespace schemac
