#include "model.h"

#include <sstream>
#include <string>

namespace schemac {

namespace {

// Table cells cannot contain newlines.
std::string one_line(const std::string& doc) {
  std::string out = doc;
  for (char& c : out) {
    if (c == '\n') c = ' ';
  }
  return out;
}

std::string default_text(const Field& f) {
  switch (f.default_kind) {
    case DefaultKind::None: return f.type.kind == TypeExpr::Kind::Optional ? "none" : "value-initialized";
    case DefaultKind::Null: return "none";
    case DefaultKind::EmptyArray: return "empty";
    case DefaultKind::String: return "\"" + f.default_text + "\"";
    default: return f.default_text;
  }
}

}  // namespace

std::string emit_docs(const Model& model, const SchemaFile& file) {
  (void)model;
  std::ostringstream out;
  out << "# Schema `" << file.ns << "` (" << file.stem << ".schema)\n\n";
  out << "Generated by schemac. Edit the schema, not this file.\n\n";
  if (!file.imports.empty()) {
    out << "Imports:";
    for (const std::string& imp : file.imports) out << " `" << imp << ".schema`";
    out << "\n\n";
  }
  for (const EnumDecl& e : file.enums) {
    out << "## enum `" << e.name << "` : " << e.underlying << "\n\n";
    if (!e.doc.empty()) out << e.doc << "\n\n";
    out << "| Name | Value | Doc |\n|---|---|---|\n";
    for (const EnumValue& v : e.values) out << "| `" << v.name << "` | " << v.value << " | " << one_line(v.doc) << " |\n";
    out << "\n";
  }
  for (const StructDecl& s : file.structs) {
    out << "## struct `" << s.name << "` (version " << s.version;
    if (!s.tag.empty()) out << ", kind `" << s.tag << "`";
    out << ")\n\n";
    if (!s.doc.empty()) out << s.doc << "\n\n";
    out << "| Field | Type | Default | Since | Flags | Doc |\n|---|---|---|---|---|---|\n";
    for (const Field& f : s.fields) {
      std::string flags;
      if (f.transient) flags += "transient ";
      if (f.deprecated) flags += "deprecated ";
      out << "| `" << f.name << "` | `" << idl_type(f.type) << "` | " << default_text(f) << " | " << f.since << " | " << flags
          << " | " << one_line(f.doc) << " |\n";
    }
    out << "\n";
  }
  return out.str();
}

}  // namespace schemac
