# cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<name> -P EmbedFile.cmake
# Writes a header declaring the input's bytes as a 4-byte-aligned constexpr array in
# namespace engine::shaders.
if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "EmbedFile.cmake: INPUT, OUTPUT, and SYMBOL are required")
endif()
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_length)
math(EXPR _byte_count "${_hex_length} / 2")
# "0a1b2c" -> "0x0a,0x1b,0x2c,"
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
# Break into lines of 16 bytes for readable diffs.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n  " _bytes "${_bytes}")
get_filename_component(_input_name "${INPUT}" NAME)
set(_content "// Generated by cmake/EmbedFile.cmake from ${_input_name}; do not edit.\n")
string(APPEND _content "#pragma once\n\n#include <cstddef>\n\nnamespace engine::shaders {\n\n")
string(APPEND _content "inline constexpr std::size_t ${SYMBOL}_size = ${_byte_count};\n")
string(APPEND _content "alignas(4) inline constexpr unsigned char ${SYMBOL}[] = {\n  ${_bytes}\n};\n\n")
string(APPEND _content "}  // namespace engine::shaders\n")
file(WRITE "${OUTPUT}" "${_content}")
