# cmake -DENGINE_SOURCE_DIR=<checkout> -DENGINE_STAMP_DIR=<dir> -P WriteBuildStamp.cmake
#
# Writes <dir>/include/engine_build_stamp.h and <dir>/engine_build_stamp.cpp: the commit the
# checkout is at and whether its tracked files differ from it. Run at configure time and again on
# every build by the `engine_build_stamp_update` target (cmake/EngineBuildStamp.cmake says why).
#
# A file is rewritten only when its content changed, so a build after no commit leaves both files
# alone and Ninja's restat recompiles and relinks nothing.

set(_commit "unknown")
set(_dirty "false")
find_program(_git NAMES git)
if(_git)
  execute_process(COMMAND "${_git}" -C "${ENGINE_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE _head RESULT_VARIABLE _rc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_rc EQUAL 0 AND _head MATCHES "^[0-9a-f]+$")
    set(_commit "${_head}")
    # --no-optional-locks: a build must never take index.lock from under a person's own git
    # command, which a plain `git status` does to refresh the index. Untracked files are not a
    # difference from the commit the binary names; tracked edits are.
    execute_process(COMMAND "${_git}" --no-optional-locks -C "${ENGINE_SOURCE_DIR}" status --porcelain --untracked-files=no
      OUTPUT_VARIABLE _status RESULT_VARIABLE _rc2 ERROR_QUIET)
    if(_rc2 EQUAL 0 AND NOT "${_status}" STREQUAL "")
      set(_dirty "true")
    endif()
  endif()
endif()

function(_write_if_changed path content)
  if(EXISTS "${path}")
    file(READ "${path}" _old)
    if("${_old}" STREQUAL "${content}")
      return()
    endif()
  endif()
  file(WRITE "${path}" "${content}")
endfunction()

_write_if_changed("${ENGINE_STAMP_DIR}/include/engine_build_stamp.h"
"// Generated by cmake/WriteBuildStamp.cmake; never edited (cmake/EngineBuildStamp.cmake).
#pragma once

namespace engine::build_stamp {

// The commit the checkout was at when this binary was *built* (not when its build tree was
// configured), 40 hex characters, or \"unknown\" where there was no git to ask (the Linux container
// syncs the tree without .git).
const char* commit() noexcept;
// Whether tracked files differed from that commit when it was built.
bool dirty() noexcept;

}  // namespace engine::build_stamp
")

_write_if_changed("${ENGINE_STAMP_DIR}/engine_build_stamp.cpp"
"// Generated by cmake/WriteBuildStamp.cmake on every build; never edited.
#include <engine_build_stamp.h>

namespace engine::build_stamp {

const char* commit() noexcept { return \"${_commit}\"; }
bool dirty() noexcept { return ${_dirty}; }

}  // namespace engine::build_stamp
")
